// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kfccagrpqidllhjqekmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmY2NhZ3JwcWlkbGxoanFla21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDE3MjIsImV4cCI6MjA3MDY3NzcyMn0.MBzTCS7X9a6yD15OpNgDOB_AcCrWsE7AM9Ei5YGRVCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);